### ISSUE TITLE
Dataset is missing ! No such file or directory: 'stop.xlsx'

### ISSUE THREAD

**Issue by rafikfartas** [hamzachataoui/NLP-for-arabic_dialect_Detection-TopicDetection-SentimentAnalysis#1]
Hello,
First, thank you for this project it's a huge ressource for us.
I downloaded all the modules nedded and when running "python model.py" its says (No such file or directory: 'stop.xlsx'), i guess the dataset is missing or i don't know if it's just a model and i should use my dataset instead, give us some informations ASAP please.
Thank you so much

```
C:\Users\ASUS\Desktop\M1 Info\PDL\NLP-for-arabic_dialect_Detection-TopicDetection-SentimentAnalysis-main>python model.py
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Traceback (most recent call last):
  File "model.py", line 27, in <module>
    c = pd.read_excel('stop.xlsx')
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\excel\_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\excel\_base.py", line 1191, in __init__
    ext = inspect_excel_format(
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\excel\_base.py", line 1070, in inspect_excel_format
    with get_handle(
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'stop.xlsx'
```

**Comment by hamzachataoui** [comment]
maybe i forget to upload same files
you can check this folder i think my friend upload all the files needed
https://github.com/Elmehdidebug/NLP-for-dialectDetection-TopicDetection-SentimentAnalysis

**Comment by rafikfartas** [comment]
Same problem...
Can u tell me which version of python u worked on ?

**Comment by hamzachataoui** [comment]
Dear rafik
you will find attached the file 'stop.xlsx'
good luk

**Comment by rafikfartas** [comment]
Thanks
Note these 3 missing files :
- stop.xlsx
- Sentiments_Analysis.xlsx
- Sentiments_Analysis_labledData.xlsx

**Comment by hamzachataoui** [comment]
Dear rafik
you will find attached all the file needed .

très bon journée
HAMZA
